/* Fintella Floating Widget Loader v1.0.0 */
import { NextRequest } from "next/server";

const PORTAL_URL =
  process.env.NEXTAUTH_URL?.replace(/\/$/, "") || "https://fintella.partners";

export async function GET(req: NextRequest) {
  const key = req.nextUrl.searchParams.get("key") || "";
  if (!key) {
    return new Response("/* Fintella: missing key param */", {
      status: 400,
      headers: { "Content-Type": "application/javascript; charset=utf-8" },
    });
  }
  const js = buildLoaderScript(key);
  return new Response(js, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
      "Access-Control-Allow-Origin": "*",
    },
  });
}

function buildLoaderScript(apiKey: string): string {
  const widgetUrl = `${PORTAL_URL}/widget?apiKey=${apiKey}&mode=float`;
  const safeWidgetUrl = JSON.stringify(widgetUrl);

  return [
    "/* Fintella Floating Widget Loader v1.0.0 */",
    "(function(){",
    '"use strict";',
    "if(window.__fintella_widget_loaded)return;",
    "window.__fintella_widget_loaded=true;",
    "",
    "var WIDGET_URL=" + safeWidgetUrl + ";",
    "var Z=2147483647;",
    "",
    "var scripts=document.querySelectorAll('script[src*=loader]');",
    "var scriptEl=scripts[scripts.length-1];",
    "var position=(scriptEl&&scriptEl.getAttribute('data-position'))||'bottom-right';",
    "var customColor=(scriptEl&&scriptEl.getAttribute('data-color'))||'#c4a050';",
    "var isLeft=position==='bottom-left';",
    "",
    "var isOpen=false;",
    "var storageKey='__fintella_widget_state';",
    "try{var saved=localStorage.getItem(storageKey);if(saved==='open')isOpen=true;}catch(e){}",
    "",
    "var host=document.createElement('div');",
    "host.id='fintella-widget-host';",
    "host.style.cssText='all:initial;position:fixed;bottom:0;'+(isLeft?'left:0;':'right:0;')+'z-index:'+Z+';pointer-events:none;width:0;height:0;';",
    "document.body.appendChild(host);",
    "var shadow=host.attachShadow({mode:'closed'});",
    "",
    "var style=document.createElement('style');",
    "style.textContent=[",
    "':host{all:initial;}',",
    "'*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}',",
    "'.fw-c{position:fixed;bottom:20px;'+(isLeft?'left:20px;':'right:20px;')+'z-index:'+Z+';font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;pointer-events:auto;}',",
    "'.fw-btn{width:60px;height:60px;border-radius:50%;border:none;cursor:pointer;background:linear-gradient(135deg,'+customColor+',#f0d070);box-shadow:0 4px 20px rgba(0,0,0,0.3);display:flex;align-items:center;justify-content:center;transition:transform 0.3s cubic-bezier(0.34,1.56,0.64,1),box-shadow 0.3s;position:relative;}',",
    "'.fw-btn:hover{transform:scale(1.1);box-shadow:0 6px 28px rgba(0,0,0,0.35),0 0 0 4px rgba(196,160,80,0.2);}',",
    "'.fw-btn:active{transform:scale(0.95);}',",
    "'.fw-badge{position:absolute;top:2px;right:2px;width:14px;height:14px;border-radius:50%;background:#ef4444;border:2px solid #fff;animation:fw-p 2s ease-in-out infinite;}',",
    "'@keyframes fw-p{0%,100%{transform:scale(1);opacity:1;}50%{transform:scale(1.3);opacity:0.7;}}',",
    "'.fw-panel{position:absolute;bottom:70px;'+(isLeft?'left:0;':'right:0;')+'width:400px;height:620px;border-radius:16px;overflow:hidden;box-shadow:0 16px 48px rgba(0,0,0,0.4),0 0 0 1px rgba(255,255,255,0.06);transform-origin:bottom '+(isLeft?'left':'right')+';transition:transform 0.35s cubic-bezier(0.34,1.56,0.64,1),opacity 0.25s;background:#060a14;}',",
    "'.fw-panel.closed{transform:scale(0.5) translateY(20px);opacity:0;pointer-events:none;}',",
    "'.fw-panel.open{transform:scale(1) translateY(0);opacity:1;pointer-events:auto;}',",
    "'.fw-hdr{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;background:linear-gradient(135deg,#0c1220,#060a14);border-bottom:1px solid rgba(255,255,255,0.06);}',",
    "'.fw-title{font-size:13px;font-weight:700;background:linear-gradient(135deg,'+customColor+',#f0d070);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:0.3px;}',",
    "'.fw-x{width:28px;height:28px;border-radius:50%;border:none;cursor:pointer;background:rgba(255,255,255,0.06);color:rgba(255,255,255,0.6);display:flex;align-items:center;justify-content:center;font-size:16px;line-height:1;transition:all 0.2s;}',",
    "'.fw-x:hover{background:rgba(255,255,255,0.12);color:#fff;}',",
    "'.fw-if{width:100%;height:calc(100% - 44px);border:none;display:block;background:#060a14;}',",
    "'@media(max-width:767px){',",
    "'.fw-panel{position:fixed;top:0;left:0;right:0;bottom:0;width:100%!important;height:100%!important;border-radius:0;}',",
    "'.fw-panel.closed{transform:translateY(100%);opacity:0;}',",
    "'.fw-panel.open{transform:translateY(0);opacity:1;}',",
    "'}'",
    "].join('\n');",
    "shadow.appendChild(style);",
    "",
    "var container=document.createElement('div');",
    "container.className='fw-c';",
    "",
    "var panel=document.createElement('div');",
    "panel.className='fw-panel '+(isOpen?'open':'closed');",
    "",
    "var hdr=document.createElement('div');",
    "hdr.className='fw-hdr';",
    "var ttl=document.createElement('span');",
    "ttl.className='fw-title';",
    "ttl.textContent='FinStellaTMS';",
    "var xBtn=document.createElement('button');",
    "xBtn.className='fw-x';",
    "xBtn.innerHTML='\u2715';",
    "xBtn.setAttribute('aria-label','Close widget');",
    "hdr.appendChild(ttl);",
    "hdr.appendChild(xBtn);",
    "panel.appendChild(hdr);",
    "",
    "var iframe=document.createElement('iframe');",
    "iframe.className='fw-if';",
    "iframe.setAttribute('allow','clipboard-write');",
    "iframe.setAttribute('loading','lazy');",
    "iframe.title='Fintella Widget';",
    "if(isOpen)iframe.src=WIDGET_URL;",
    "panel.appendChild(iframe);",
    "container.appendChild(panel);",
    "",
    "var btn=document.createElement('button');",
    "btn.className='fw-btn';",
    "btn.setAttribute('aria-label','Open Fintella widget');",
    "btn.innerHTML='<svg viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><text x=\"50%\" y=\"54%\" dominant-baseline=\"central\" text-anchor=\"middle\" font-family=\"Georgia,serif\" font-size=\"24\" font-weight=\"700\" fill=\"#060a14\">F</text></svg>';",
    "",
    "var badge=document.createElement('div');",
    "badge.className='fw-badge';",
    "var bKey='__fintella_badge_seen';",
    "try{if(localStorage.getItem(bKey))badge.style.display='none';}catch(e){}",
    "btn.appendChild(badge);",
    "container.appendChild(btn);",
    "shadow.appendChild(container);",
    "",
    "function toggle(){",
    "  isOpen=!isOpen;",
    "  panel.className='fw-panel '+(isOpen?'open':'closed');",
    "  if(isOpen&&!iframe.src)iframe.src=WIDGET_URL;",
    "  try{",
    "    localStorage.setItem(storageKey,isOpen?'open':'closed');",
    "    if(isOpen)localStorage.setItem(bKey,'1');",
    "  }catch(e){}",
    "  if(isOpen)badge.style.display='none';",
    "  btn.setAttribute('aria-label',isOpen?'Close Fintella widget':'Open Fintella widget');",
    "}",
    "",
    "btn.addEventListener('click',toggle);",
    "xBtn.addEventListener('click',function(e){e.stopPropagation();if(isOpen)toggle();});",
    "",
    "window.addEventListener('message',function(e){",
    "  if(!e.data||typeof e.data!=='object')return;",
    "  var t=e.data.type;",
    "  if(t==='fintella:close'&&isOpen)toggle();",
    "  if(t==='fintella:referral_submitted'){",
    "    badge.style.display='block';",
    "    badge.style.background='#22c55e';",
    "    try{localStorage.removeItem(bKey);}catch(ex){}",
    "  }",
    "});",
    "",
    "})();",
  ].join("\n");
}
